# Launching
bind = SUPER, semicolon, exec, pkill wofi || wofi --show drun # -O alphabetical
bind = SUPER SHIFT, slash, exec, pkill wofi || ~/.local/share/omarchy/bin/omarchy-menu-keybindings

# Aesthetics
bind = SUPER SHIFT, SPACE, exec, pkill -SIGUSR1 waybar
bind = SUPER CTRL, SPACE, exec, ~/.local/share/omarchy/bin/omarchy-theme-bg-next
bind = SUPER SHIFT CTRL, SPACE, exec, pkill wofi || ~/.local/share/omarchy/bin/omarchy-theme-menu

# Notifications
bind = SUPER, comma, exec, makoctl dismiss
bind = SUPER SHIFT, comma, exec, makoctl dismiss --all
bind = SUPER CTRL, comma, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications"

# Power menu controls lock, suspend, relaunch, restart, shutdown
bind = SUPER, ESCAPE, exec, pkill wofi || ~/.local/share/omarchy/bin/omarchy-menu-power

# Toggle idling
bind = SUPER CTRL, I, exec, ~/.local/share/omarchy/bin/omarchy-toggle-idle

# Control Apple Display brightness
bind = CTRL, F1, exec, ~/.local/share/omarchy/bin/omarchy-apple-display-brightness -5000
bind = CTRL, F2, exec, ~/.local/share/omarchy/bin/omarchy-apple-display-brightness +5000
bind = SHIFT CTRL, F2, exec, ~/.local/share/omarchy/bin/omarchy-apple-display-brightness +60000

# Screenshots
bind = , PRINT, exec, hyprshot -m region
bind = SHIFT, PRINT, exec, hyprshot -m window
bind = CTRL, PRINT, exec, hyprshot -m output

# Color picker
bind = SUPER, PRINT, exec, hyprpicker -a

bind = SUPER, V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy

# Submap keybinds
$sm-reset = hyprctl dispatch submap reset

$sm-msg = (D)iscord (T)elegram (S)ignal
submap=$sm-msg
	bind= , escape, submap, reset
	bind = , D, exec, $sm-reset; uwsm app -- discord
	bind = , T, exec, $sm-reset; uwsm app -- telegram-desktop
	bind = , S, exec, $sm-reset; uwsm app -- signal-desktop
submap=reset

$sm-player = (P)revious (T)oggle (N)ext
submap=$sm-player
	bind= , escape, submap, reset
	bind = , N, exec, $sm-reset; playerctl next
	bind = , P, exec, $sm-reset; playerctl previous
	bind = , T, exec, $sm-reset; playerctl play-pause
submap=reset

$sm-window-resize = Resizing: HJKL
submap=$sm-window-resize
	bind= , escape, submap, reset
	bind = , H, resizeactive, -100 0
	bind = , L, resizeactive, 100 0
	bind = , K, resizeactive, 0 -100
	bind = , J, resizeactive, 0 100
submap=reset

$sm-window = (R)esize
submap=$sm-window
	bind= , escape, submap, reset
    bind = , R, submap, $sm-window-resize
submap=reset

# $set_overlay = bash -c "source .local/share/omarchy/scripts/set_overlay.sh '(M)sg (P)layer'"

$sm-leader = (M)sg (P)layer (W)indow
# bind = SUPER, space, submap, $sm-leader
# bind = SUPER, space, exec, hyprctl dispatch submap leader; echo "(M)sg (P)layer" | $set_overlay
# bind = SUPER, space, exec, hyprctl dispatch submap leader; $set_overlay "(M)sg (P)layer"
bind = SUPER, space, submap, $sm-leader
submap=$sm-leader
    # bind= , escape , submap, reset
    bind= , escape, exec, hyprctl dispatch submap reset; pkill -f "foot-overlay"
    bind = , M, submap, $sm-msg
    bind = , P, submap, $sm-player
    bind = , W, submap, $sm-window
submap=reset